import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../../components/ui/navbar";
import {ReactLenis} from '@/utils/lenis'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "webapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <ReactLenis root>
        <body
          className={`font-Dm_sans ${geistSans.variable} ${geistMono.variable} antialiased `}
        >
            <Navbar/>
            {children} 
        </body>
      </ReactLenis>
      
    </html>
  );
}
